[package]
name = "ouch"
version = "0.4.0"
authors = ["Vinícius Rodrigues Miguel <vrmiguel99@gmail.com>", "João M. Bezerra <marcospb19@hotmail.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/ouch-org/ouch"
license = "MIT"
keywords = ["decompression", "compression", "zip", "tar", "gzip", "accessibility", "a11y"]
categories = ["command-line-utilities", "compression", "encoding"]
description = "A command-line utility for easily compressing and decompressing files and directories."

[dependencies]
atty = "0.2.14"
bzip2 = "0.4.3"
clap = { version = "4.0.26", features = ["derive", "env"] }
filetime = "0.2.18"
flate2 = { version = "1.0.24", default-features = false }
fs-err = "2.9.0"
humansize = "2.1.2"
ignore = "0.4.18"
libc = "0.2.137"
linked-hash-map = "0.5.6"
lzzzz = "1.0.4"
once_cell = "1.16.0"
same-file = "1.0.6"
snap = "1.1.0"
tar = "0.4.38"
tempfile = "3.3.0"
xz2 = "0.1.7"
zip = { version = "0.6.3", default-features = false, features = ["time"] }
zstd = { version = "0.12.0", default-features = false }
# zstd-sys > 2.0.1 unconditionally enables thin LTO and causes CI to fail
# https://github.com/gyscos/zstd-rs/pull/155
zstd-sys = "=2.0.1"

[target.'cfg(unix)'.dependencies]
time = { version = "0.3.17", default-features = false }

[target.'cfg(not(unix))'.dependencies]
is_executable = "1.0.1"

[build-dependencies]
clap = { version = "4.0.26", features = ["derive", "env", "string"] }
clap_complete = "4.0.5"
clap_mangen = "0.2.4"

[dev-dependencies]
assert_cmd = "2.0.6"
infer = "0.11.0"
parse-display = "0.6.0"
proptest = "1.0.0"
rand = { version = "0.8.5", default-features = false, features = ["small_rng", "std"] }
test-strategy = "0.2.1"

[features]
default = ["flate2/zlib", "zip/deflate-zlib", "zstd/thin"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
