[package]
name = "ouch"
version = "0.3.1"
authors = ["Vinícius Rodrigues Miguel <vrmiguel99@gmail.com>", "João M. Bezerra <marcospb19@hotmail.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/ouch-org/ouch"
license = "MIT"
keywords = ["decompression", "compression", "zip", "tar", "gzip", "accessibility", "a11y"]
categories = ["command-line-utilities", "compression", "encoding"]
description = "A command-line utility for easily compressing and decompressing files and directories."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
bzip2 = "0.4.3"
clap = { version = "3.1.18", features = ["derive", "env"] }
flate2 = { version = "1.0.24", default-features = false }
fs-err = "2.7.0"
libc = "0.2.126"
linked-hash-map = "0.5.4"
lzzzz = "1.0.3"
once_cell = "1.12.0"
snap = "1.0.5"
tar = "0.4.38"
xz2 = "0.1.6"
zip = { version = "0.6.2", default-features = false }
zstd = { version = "0.11.2", default-features = false }
tempfile = "3.3.0"
ignore = "0.4.18"
indicatif = "0.16.2"

[target.'cfg(unix)'.dependencies]
time = { version = "0.3.9", default-features = false }

[build-dependencies]
clap = { version = "3.1.18", features = ["derive", "env"] }
clap_complete = "3.1.4"

[dev-dependencies]
assert_cmd = "2.0.4"
infer = "0.8.0"
parse-display = "0.5.5"
proptest = "1.0.0"
rand = { version = "0.8.5", default-features = false, features = ["small_rng", "std"] }
test-strategy = "0.2.0"

[features]
default = ["flate2/zlib", "zip/deflate-zlib", "zstd/thin"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
